### ISSUE TITLE
Further Essential Columns

### ISSUE THREAD

**Issue by callumjclarke** [dmpstats/Standardise_Formats_and_Calculate_Basic_Statistics#12]
As previously discussed, the column `local_timestamp` created by `Add local and solar time` will be used in classification - whenever the next release comes, we should add this to the `keepessentials` list on line 351-374 (low priority). Likely that other columns will need to be added too, so I'll update this issue as they come.

**Comment by callumjclarke** [comment]
Miscellaneous further thoughts on the other `essentialcols` that could clean the data up a bit:

- `mins`, `secs` can probably be removed - I can't think of any later use of these two
- I think `x`, `y` are also not used again (as we can just extract their contents using `st_coordinates()` down the pipeline). Even if they're useful at a later date (e.g. for merging into ER), removing them would clean things up a little given that they can be binded easily at any point

**Comment by bcaneco** [comment]
Left columns `mins` and `secs` in there, for the moment, as I think there is actually a case for dropping binding of any time-related columns in the App - i.e. remove the `bind_times` option from settings. 

Basically, these columns can be generated on the fly within each App as required (e.g. based on UTC or local time as appropriate). Will open this in a new issue for future consideration :)

Closing this issue as it's resolved, as far as I can see.
