### ISSUE TITLE
Improve handling of defaults for column naming parameters

### ISSUE THREAD

**Issue by bcaneco** [dmpstats/Standardise_Formats_and_Calculate_Basic_Statistics#15]
- In appspec.json, change defaults for `idcol`, `altitudecol`, `tempcol` and `headingcol` from `""` to `NULL`
- Adapt code accordingly, taking into account that current version overwrites an existent column if the input is left blank/null.

For example:

https://github.com/dmpstats/Standardise_Formats_and_Calculate_Basic_Statistics/blob/670e4b7538cfd48a099b7ac554e4c1100648b504/RFunction.R#L150-L158

Means that, if the user leaves `headingcol` blank/null, and if the column `heading` is already present in the input (which is common), then `heading` will be overwritten with NAs

**Comment by andreakoelzsch** [comment]
@bcaneco, did you really already catch our updates from yesterday that now set the string "" equal to NULL?

**Comment by bcaneco** [comment]
Not intentionally @andreakoelzsch! 😄 

I was just generating some testing datasets and noticed a bug in this app, which led me to consider switching default "" inputs to NULLs would be more appropriate. 

Nevertheless, thanks for the heads-up on the change in the parsing of NULL in the Settings interface! So that means Settings now respects the definition of NULL defaults from appspecs, right? In other words, "" and NULL in appspecs are now construed as different inputs?

**Comment by andreakoelzsch** [comment]
HI @bcaneco, not quite like it. Before, we were allowing "" and NULL to be different settings, but if ever a user entered some number to the Settings, it was impossible to get back to NULL value. Therefore, we have decided to handle "" as if it was NULL for the App code (I have not tested this properly, though, brand new, sorry). So, the appspec is now properly parsing the default NULL from appspec (which it did not before) in a STRING setting and gets back to it if "" is reached by the user.
We really could not thing of a usage of "" that was different from NULL. Or, do you have any use case where both are really important cases that are required?

**Comment by bcaneco** [comment]
Yep, agreed - that's exactly my preferred behaviour, i.e. 
 - blank inputs in Settings are always passed on the the App function as NULL
 - NULL defaults from appspec to appear as NULL in the Settings (with the existent tip below the input field)

Great work! 😉
