### ISSUE TITLE
issue selecting `primary animal identifier`

### ISSUE THREAD

**Issue by lindesaysh** [dmpstats/Standardise_Formats_and_Calculate_Basic_Statistics#19]
If you would like to select the primary identifier for each track/tag/animal then this currently can only select from a column in the event data component of the move2 object.  

For example, if you would like to select `individual_local_identifier` as the column to represent track id this is not possible as the column is in the track data and not the event data. 

Suggested solution:
- to add code to be able to select track information as the identifier.

**Comment by callumjclarke** [comment]
Might be worth fixing this with a trycatch or ifelse:
- Try to find identifier column in event data 
- If fails, check in track data 
- If neither, column unavailable

**Comment by bcaneco** [comment]
App updated with option to re-assign track ID to columns in track component of input `move2` object now available online to all users on MoveApps.
