### ISSUE TITLE
build on MoveApps

### ISSUE THREAD

**Issue by andreakoelzsch** [dmpstats/Standardise_Formats_and_Calculate_Basic_Statistics#9]
Hi @bcaneco and @callumjclarke, the building of your updated version of this App fails to some R package intall problems. I can only discuss that with our developer on Monday, will come back to you about it then. Sorry for the delay.

**Comment by bcaneco** [comment]
Thanks for the heads up @andreakoelzsch. Hopefully it's nothing too serious to resolve!

**Comment by bcaneco** [comment]
Hi @andreakoelzsch - I can see the issue with the app building has resolved. Thanks! 

Closing this issue as resolved.
